name: Build OpenVidu Components Angular
description: Builds and packages the OpenVidu Components Angular library as a GitHub artifact
inputs:
  repository:
    description: 'Repository to checkout for OpenVidu Components Angular'
    required: false
    default: 'OpenVidu/openvidu'
  checkout_ref:
    description: 'Branch, tag, or commit to checkout'
    required: false
    default: 'master'
  artifact_name:
    description: 'Name of the artifact to upload'
    required: false
    default: 'openvidu-components-angular'
outputs:
  artifact_name:
    description: 'Name of the uploaded artifact'
    value: ${{ inputs.artifact_name }}
  package_filename:
    description: 'Filename of the built package'
    value: ${{ steps.build.outputs.package_filename }}
runs:
  using: 'composite'
  steps:
    - name: Checkout OpenVidu Components Angular
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.checkout_ref }}
        path: components-source

    - name: Build OpenVidu Components Angular
      id: build
      shell: bash
      run: |
        echo "Building OpenVidu Components Angular..."

        # Define common paths
        COMPONENTS_DIR="components-source/openvidu-components-angular"
        DIST_DIR="$COMPONENTS_DIR/dist/openvidu-components-angular"
        PACKAGE_NAME="openvidu-components-angular.tgz"

        # Install dependencies and build the library
        cd "$COMPONENTS_DIR"
        npm install
        npm run lib:build

        # Package the built library
        npm run lib:pack

        # Rename to standard name for easier handling
        mv "$DIST_DIR"/openvidu-components-angular-*.tgz "$DIST_DIR/$PACKAGE_NAME"

        echo "package_filename=$PACKAGE_NAME" >> "$GITHUB_OUTPUT"
        echo "OpenVidu Components Angular built successfully"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: components-source/openvidu-components-angular/dist/openvidu-components-angular/openvidu-components-angular.tgz
