name: Start OpenVidu Meet
description: Checkout and start OpenVidu Meet and wait for it to be ready
inputs:
  timeout:
    description: Maximum time to wait for OpenVidu Meet to start (in milliseconds)
    required: false
    default: '60000'
runs:
  using: "composite"
  steps:
    - name: Setup yarn # Needed for the redlock package
      shell: bash
      run: npm install -g yarn
    - name: Checkout OpenVidu Meet
      uses: actions/checkout@v4
    - name: Prepare OpenVidu Meet
      shell: bash
      run: |
        ./prepare.sh
        cd backend
        npm run start:prod &
    - name: Wait for OpenVidu Meet to Start
      shell: bash
      run: wait-on --timeout ${{ inputs.timeout }} http://localhost:6080/meet/health
